version: '3.8'

services:
  backend:
    build: .
    container_name: pokemon-battle-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: pokemon-battle-db
    volumes:
      - sqlite-db:/data

volumes:
  sqlite-db:


