version: '3.8'

services:
  backend:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./pokemon-battle
    volumes:
      - ./pokemon-battle:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: sqlite
    volumes:
      - ./sqlite:/var/lib/sqlite
    environment:
      SQLITE_DATABASE: 'pokemon-battle.db'
